server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_db
    username: accounts_ms
    password: tu_password_segura
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "com.investment.*"
        enable.idempotence: true
    consumer:
      group-id: accounts-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.investment.*"
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:          # <-- corregido (antes estaba mal escrito)
        jwt:
          jwk-set-uri: http://localhost:8080/realms/investment/protocol/openid-connect/certs

app:
  kafka:
    topics:
      tradeExecuted: trades-trades-executed
      positionsRecalculateRequested: positions-recalculate-requested

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace