server:
  port: 8082   # puedes dejarlo igual que el base o cambiarlo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_db
    username: orders_ms
    password: tu_password_segura
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # en local permitimos crear/actualizar

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "com.investment.*"
      acks: all
      retries: 5
      enable-idempotence: true
    consumer:
      group-id: orders-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.investment.*"
      auto-offset-reset: earliest

app:
  kafka:
    topics:
      orderCreated: orders.order-created
      tradeExecuted: trades.trade-executed

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace