server:
  port: ${PORT:8082}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:investment_db}
    username: ${DB_USER:orders_ms}
    password: ${DB_PASS:super_segura}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # en prod NUNCA 'update'

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "com.investment.*"
      acks: all
      retries: 5
      enable-idempotence: true
    consumer:
      group-id: ${KAFKA_GROUP:orders-ms}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.investment.*"
      auto-offset-reset: earliest

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false