server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:investment_db}
    username: ${DB_USER:portfolios_ms}
    password: ${DB_PASS:super_segura}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # explícito (o puedes omitirlo: ya lo trae el base)

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false