spring:
  application:
    name: positions-ms

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: positions
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html